version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: Metro1102
      POSTGRES_PASSWORD: vpCzk!gVZ2jz
      POSTGRES_DB: althea
    ports:
      - "5432:5432"
  cache:
    image: redis
    ports:
      - "6379:6379"
